version: '3.8'

services:
    frontend:
        container_name: desktop-ims-frontend
        build:
            context: ./
            dockerfile: dockerfile.frontend.dev
        volumes:
            - ./frontend:/opt/desktop-ims-frontend/
        ports:
            - '3000:3000'
        networks:
            - desktop-ims

    server:
        container_name: desktop-ims-server
        build:
            context: ./
            dockerfile: dockerfile.server.dev
        environment:
            NODE_ENV: development
        volumes:
            - ./server:/opt/desktop-ims-server/
        ports:
            - '4000:4000'
        networks:
            - desktop-ims
        depends_on:
            - db

    db:
        container_name: desktop-ims-db
        image: bitnami/mongodb:5.0
        volumes:
            - ./data:/data
        networks:
            - desktop-ims
        logging:
            driver: none
        environment:
            MONGODB_REPLICA_SET_MODE: primary
            ALLOW_EMPTY_PASSWORD: 'yes'

    db_gui:
        container_name: 'desktop-ims-db-gui'
        image: ugleiton/mongo-gui
        ports:
            - '3001:4321'
        environment:
            - MONGO_URL=mongodb://desktop-ims-db
        networks:
            - desktop-ims
        depends_on:
            - db

networks:
    desktop-ims:
        name: desktop-ims
        external: false
