version: '3.8'

services:
    frontend:
        image: jtjeruta/ims-frontend:latest
        ports:
            - '3000:3000'
        networks:
            - desktop-ims
        restart: 'always'

    server:
        image: jtjeruta/ims-server:latest
        environment:
            NODE_ENV: production
        ports:
            - '4000:4000'
        networks:
            - desktop-ims
        depends_on:
            - mongo1
        restart: 'always'

    mongo1:
        container_name: mongo1
        image: bitnami/mongodb:5.0
        volumes:
            - ./data:/data
        networks:
            - desktop-ims
        ports:
            - 30001:27017
        logging:
            driver: none
        environment:
            MONGODB_REPLICA_SET_MODE: 'primary'
            ALLOW_EMPTY_PASSWORD: 'yes'
        restart: 'always'

networks:
    desktop-ims:
        name: desktop-ims
        external: false
