#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd frontend
echo "Formatting frontend..."
npx pretty-quick --staged

cd ../server
echo "\nFormatting backend..."
npx pretty-quick --staged
echo "\n"

